# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  brace-style:
    - 2
    -
      style: 1tbs
  mixins-before-declarations:
    - 2
    - exclude: [
      'breakpoint',
      'grid-media',
      'mod-list',
      'mq'
    ]
  no-ids: 2
  no-important: 2
  hex-length:
    - 1
    -
      style: long
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 1
  leading-zero:
    - 1
    -
      include: true
  property-sort-order:
    - 1
    -
      order:
        -
      ignore-custom-properties: true
  pseudo-element:
    - 2
  single-line-per-selector:
    - 2
  space-after-colon:
    - 2
  quotes:
    - 1
    - style: single
  zero-unit:
    - 2
    -
      include: false
